version: 2
before:
  hooks:
    - go mod tidy
    - git diff --exit-code go.mod go.sum
builds:
  - main: ./cmd/clone
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
archives:
  - format: binary

changelog:
  sort: asc
